### ISSUE TITLE
Convex? defined in two locations

### ISSUE THREAD

**Issue by idolesta16** [idolesta16/racket-collision-detection#3]
It appears that a definition for the same function convex? appears in baisc-data-structures.rkt and colllisions.rkt. I'll go in and make a provide/require if necessary.

**Comment by idolesta16** [comment]
This is in the debioka-patch-1 branch

**Comment by debioka** [comment]
The internal one is a data field of tpe boolean for a struct
It's bad practice so give it another name i'd say
